### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by ddugovic**
A place to discuss ideas with @mnemi per his suggestion.

### CODE REVIEW

**Comment by ghost** [comment]
Just saw this so I'll put my message here instead:

I've given up on Angular 1. It's really, really complicated with all of it's $scope nonsense and I can never tell what scope is where and which controllers/components have access to what scope. Not to mention I can't even tell when the damn digest cycle is started whenever the socket gets data. I just can't wrap my head around it. I'd rather invest my time learning ES6 modules and classes because at least those seem to be around to stay. Sorry Dan, but I'm gonna give up on this one.

**Comment by ddugovic** [comment]
No worries, I too think a rewrite makes more sense than iterative refactors.  Thanks for looking into it.

**Comment by ghost** [comment]
Just noticed this because notifications are off on this account :man_facepalming:. 

In terms of the `systemd` approach, it's a bit hard to ask users to install a `systemd` unit on their system just to develop an app (yes, there are systemd user services, but that's a can of worms I'm not experienced with). It's also a bit brittle considering the hard-coded path and user dependencies.

`npm` was not managing anything here. It was simply starting `mongodb` as the user so that you could develop without having to escalate privileges with `sudo`. `apt` would still have had to be used to install the dependencies.

The question here is one of "`apt` and `systemd` along with provisioning the server manually" vs "`docker` and `<insert provisioning & config management engine here>` to do all that for us". I have a personal preference for the latter because I find setting up a server and then having to ssh in over and over again tedious and error-prone, but maybe you don't find it such an issue. Ultimately, you are the one dedicating your time and hardware to run the server, so when it comes to decisions related to that I must respect your choices.

To be honest, it's really only us working on this, so this is mostly an excuse for me to try docker :stuck_out_tongue:. It probably won't afford us much over npm/shell scripts. However, something to automate provisioning of the server and deploying new releases (ansible, chef, tons of other choices) would definitely be worth looking into.

**Comment by ddugovic** [comment]
Sorry, I conflated `docker` (or other provisioning systems) and `npm` (we were discussing docker and this code uses `npm` to start `mongodb` which on the production instance is already running).

I think for development provisioning tools are quite useful and I'll gladly read any documentation about ansible, chef, docker, vagrant, etc. (I've used all of these except ansible) but so far haven't found a secure, non-dedicated server substitute for `apt` (or `rpm` or similar) with `systemd` (or `upstart` or similar).

I understand that it's very useful to be able to quickly create environments on a variety of OSs for development & testing & staging etc.; in production it's useful to be able to audit system services via a uniform interface and automatically apply security updates to services without taking down applications.

**Comment by ghost** [comment]
This reminded me of a `systemd` feature I'd forgotten: [System User Services](https://wiki.archlinux.org/index.php/Systemd/User). It doesn't help with provisioning and management, but they're handy for other things, like isolation. It's a cool feature and can be used to let the app service run without privilege. [Here's](https://www.brendanlong.com/systemd-user-services-are-amazing.html) a quick article on what I mean.

**Pull request closed without merging**
