### PR TITLE
Fix the display of active games

### PR DESCRIPTION
**Pull request by ghost**
Active games were previously being displayed as `() vs ()`. This fixes that.

### CODE REVIEW

**Comment by ddugovic** [comment]
Oh wow, it's cool that this works!  I think this makes with what I attempted yesterday too.

**Comment by ghost** [comment]
Sorry, not sure where to put this. Could you enable issues for this repo so that there could be a place to log bugs/discuss potential major changes. I've got some ideas to get app more usable, but I'd like your input. Or, if you think this is a usable enough state (login,logout,rated games, anonymous users), then it might be time to rewrite?

**Comment by ddugovic** [comment]
Personally I'm thinking the rewrite is in order.

Also the original author created a Trello to track issues, although I don't understand why we couldn't have used GitHub issues instead: https://trello.com/b/4DJqgvJp/relaychess

**Comment by ghost** [comment]
For the rewrite are you thinking Elixir+Phoenix for the backend and "insert JS framework here" for the frontend? Or do you want to try something functional for the frontend as well (like Elm or Purescript)? A third option I was thinking of was to scrap the frontend, rewrite it, and just do a big refactor on the backend keeping the tech stack intact.

**Comment by ddugovic** [comment]
Elm looks exciting although I haven't yet looked at PureScript (or others; I hear chess.com uses Vue?).  But also I need to consider how challenging implementation and modification of chess rules would be.

**Comment by ghost** [comment]
Well, I've been looking over the Angular 1 docs and Vue.js 2 stuff. Seems like Vue is heavily inspired by the best parts of Angular. I think I'm going to refactor the frontend, but keep it in Angular 1, and once that's complete, if you still want a rewrite, then the transition shouldn't be terrible.

Having skimmed the Angular docs, some of this code doesn't seems like "well-architected" angular. For example, it doesn't seem to use components and separate template files which makes things much more readable. Also, the index.html is "div-soup" with inline styles everywhere. I'm not sure why it's like this; maybe there's a good reason for it?
 
The introduction of a build system, like Gulp or hand-rolled npm scripts, would probably make things easier. Making frontend dependencies explicit via a package.json and `requiring` them with Browserify is another good idea (right now the frontend dependencies are literally stored right in this repo. There's an old version of chessground.js just sitting in here.)

The backend stuff isn't too bad and there's some decent stuff that could be reused there. Express is dead-simple to get something up and running, so I think we should just keep it. Maybe switch out socket.io for express-ws and just use native WebSockets in the browser seeing as they're well-supported now. Session management might need some work, but it's probably not too bad (I saw something called `express-session` which might be useful).

Also, I've been looking at Docker and I think the introduction of Docker and Docker-compose would make testing and deployment easier. Once everything is setup, we would simply have to provision a server with Docker and Docker-compose, and then run `docker-compose up`. Everything would then be ready and pointing at the right places (mongodb, nginx, and the app).

All in all, I think there's enough here that it's worth keeping and working around. Maybe I'll change my mind once I get started. I'd appreciate your thoughts on this. Thanks!

**Comment by ddugovic** [comment]
Hmm... I'm slowly learning.  My current interest is in Phoenix/Elixir since I think FP web applications hold great promise... but I'm sure halfway through I'll learn how best to do front end (esp. chess) stuff... I'm also inspired by the scrabble applications https://github.com/Happy0 is developing although I'm more interested in Phoenix than in Scala or Haskell.

I'm open to whatever we want to do, although I don't feel esp. attached to this repository.

I agree that a build system would probably simplify things.

For the last couple months on Ubuntu 18.04 I've been waiting on Ubuntu to release `docker-ce` (so I can install https://github.com/BrandonE/lichocker ).  It seems the only way I can obtain `docker` is by adding their repo, which considerably slows all updates on my server; but eventually Ubuntu will release a version and I should be able to migrate.  I understand that being able to easily configure URIs for mongodb etc. is useful; but actually provisioning those seems easier than provisioning Docker to provision them, I think?  If we had many environments I could see the upside to using Docker.

**Comment by ghost** [comment]
I'd be down to rewrite the backend in Haskell (though my Haskell is very rusty so there'd be a lot of relearning and Haskell has a semi-steep learning curve in my experience). The Erlang VM side of things (Elixir and the like) has never really crossed my interest, but it seems to be going for a "functional ruby" style? 

For Docker try to think of it as defining a standardized setup script that could be deployed on any platform supporting it. It also alleviates the need to worry about environment (the needed libraries/images, like Node, are specified and bundled with the image). In terms of 'provisioning docker', yes, you still have to install and setup Docker on the host/server, but that's it. If you really wanted to go off the devops deep end, we could use something like ansible which would then setup the server with docker for us and run `docker-compose` to start the app. I should mention that these are all new technologies to me, but I figure this is a low-risk project and it's always fun to try new stuff!

**Comment by ddugovic** [comment]
Hm... it's been many months, but I remember being excited about Elixir but not so much about Ruby.  I found a comparison here: https://www.amberbit.com/blog/2015/12/22/when-choose-elixir-over-ruby-for-2016-projects/ .  Sorry I'm not yet qualified to speak about this.

I've used Docker before; it's just that unless I have Docker managing everything on the server (for example, the 10GB-HD 1-CPU Relay Chess server is also running my Twitch chat bot, and is running GodelEscherBot on Lichess) it's possible that Docker provisions things either inefficiently or in a way which conflicts with already-provisioned services.  I think Docker would work, I just don't think (assuming a Linux OS & assuming there aren't many environments to provision) `apt install` is also easy...?

In general I've had difficulties correctly configuring services provisioned by Docker (although admittedly `lila` setup probably wasn't the easiest place to start; nor was a Windows consumer of the Lichess API which requires secure websockets) but certainly it would work, but just because I have some experience doesn't necessarily mean I know what I'm doing, I guess.

**Comment by ghost** [comment]
The docker thing isn't a big deal. Just a suggestion because I wanted to play around with it. I'll try doing a refactor of the frontend like I said and I'll submit a pull request if I get something usable. If after the refactor it still looks like an old, unholy mess (or I cant get it working :laughing:), then I'd be convinced this repo is unsavable.

**Comment by ddugovic** [comment]
I'll definitely play with https://github.com/BrandonE/lichocker as soon as stable `docker-ce` is released for Ubuntu 18.04!

**Comment by ghost** [comment]
Ok, did a quick little overhaul. You can check it out here: https://github.com/mnemi/RelayChess . If you're in a graphical environment (i.e. a linux desktop or Windows with node and npm installed properly), you can try out the new build. Just open a terminal and run `npm run dev` and the server should start and a brower should open with the page loaded automatically. Haven't setup auto-executing mongodb yet, so it's not perfect, but it's a decent start.

A final note on Docker, it solves the problem of developing across environments quite well. Currently, I'm on Solus, but I also run Fedora 28 on my laptop. That means I've got both `eopkg` and `dnf` for package management. You are developing on Windows and deploying on an Ubuntu 18.04 machine I think? So that's `apt get`. Now we could write a start script that had a switch for all these OSes, but that quickly becomes cumbersome and it doesn't deal with the version mismatches that will inevitably occur because of the different repos of packages. Docker solves these things.

**Comment by ddugovic** [comment]
I do see that initial setup with `npm run dev` is simple.  I agree the code taxonomy should be moved around as you suggest and the readme updated, and your name or GitHub added to the authors list.  The authors list needs to contain at least one real name for MIT license to be enforceable, and should use `and` instead of `&`.

I'm currently developing from Windows SSH'd into a headless Linux server (which is inelegant but allows me to use Linux built-in sysadmin tools `apt`, `systemd`, etc.) although the first time I figured out `systemd` https://github.com/ddugovic/RelayChess/blob/master/relaychess.service was a bit cumbersome (ensuring that `network-online` and `mongodb` services are online before this project runs; and that a failing service will restart with rate-limiting, subject to `network-online` and `mongodb` still being available).

I did see that OVH-provided MongoDB (via `apt`) was secured such that I didn't need to configure permissions, firewall, etc.; and such that it works well on the low-end hardware they provisioned; and it automatically installs security updates.  I apologize for not thinking of these considerations yesterday (I was thinking about the application & wasn't thinking much about its deployment/management mechanism).

**Comment by ghost** [comment]
We really need to find a better place to put these messages  :stuck_out_tongue:. Quick update on components: I've moved out a large chunk of index.html into templates files. Once I'm finished, the end result will be neat, little components which have a template and an associated controller that have encapsulated scope. Example is the new `<navbar></navbar>` element [here](https://github.com/mnemi/RelayChess/blob/frontend-components/web/src/app/lobby/navbar/navbar.component.js).

Angular 1 is a bit complicated, but I think I see what it was trying to do for it's time: create a proper system of  encapsulations (because ES6 modules and classes didn't exist at the time).

**Comment by mnemi** [comment]
Final update. I've given up on Angular 1. It's really, really complicated with all of it's $scope nonsense and I can never tell what scope is where and which controllers/components have access to what scope. Not to mention I can't even tell when the damn digest cycle is started whenever the socket gets data. I just can't wrap my head around it. I'd rather invest my time learning ES6 modules and classes because at least those seem to be around to stay. Sorry Dan, but I'm gonna give up on this one.

**Pull request merged**
