### PR TITLE
Refactor directory structure and Webpack

### PR DESCRIPTION
**Pull request by ghost**
Separates the frontend from the backend and renames some relative paths so that everything works as normal. There's also a _shiny_ new lobby image in the `README` and a blank `package.json` for the frontend which will eventually be filled with the appropriate stuff.

### CODE REVIEW

**Comment by ghost** [comment]
**Webpack:**
All dependencies are now tracked in `package.json` and the site is built and bundled using [Webpack](https://webpack.js.org/). 

Many dependencies were upgraded to their latest versions (and some were removed) as described here: https://github.com/mnemi/RelayChess/issues/3

The code now uses modern ES6 modules, however in order to avoid a giant refactor and breaking changes, this is mostly a wrapper around AngularJS' module system. See https://github.com/mnemi/RelayChess/blob/webpack/web/src/app/app.js for what I mean. When the code is eventually refactored into components, this will be refined to reflect modern best practices.

The `Webpack` config has two parts: `development` and `production`. 

`Development` is as it sounds. Running `npm start` will spin up a `webpack-dev-server` that will watch for changes to the files, automatically re-bundle, etc., and live-reload a browser to reflect those changes.

`Production` produces the files that would be served for user consumption. Running `npm run-script build` will produce the necessary files in a directory called `dist/`. At the moment minification is disabled in the production build because the `AngularJS` dependency injector depends on a constructor's parameter names to locate and inject dependencies. Minification ruins this. The solution is to add an `$inject` property to each constructor, but that will be done later during the refactoring into components. This isn't a huge loss because the original code didn't have minification to begin with, so nothing lost, nothing gained. 

All in all, a huge improvement over having no build, and it makes many things more explicit, easier to develop, and easier to deploy.

**Comment by ghost** [comment]
@ddugovic sorry, I fumbled a bit with what was suppose to be a merge on my own repo, and now I've sort of made a mess of things with all these silly pull requests. That said, the commits are fine, and the code is tested and working. Looks pretty safe to merge. Nothing feature-wise should be broken.

**Comment by ddugovic** [comment]
Deployed to production.

**Comment by ghost** [comment]
I should mention that the configuration of where the client socket points to is still manual. So you'll need to point [it](https://github.com/ddugovic/RelayChess/blob/master/web/src/app/relayChessService.js#L19) at the right spot before running the build (or `grep` for `localhost:3000` in the `dist/app.js` and edit it appropriately). I'll make this automatic when I get a chance.

**Comment by ghost** [comment]
@ddugovic Quickfix: ec28cffa41f9d6889292c7aca1c78c862a6a7334

**Pull request merged**
